model:
  name: 'osnet_ain_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['market1501DCL']
  targets: ['market1501DCL']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'color_jitter']
  save_dir: 'log/osnet_ain_x1_0_market1501_softmax_cosinelr'

loss:
  name: 'DCL'
  softmax:
    label_smooth: True
  

train:
  optim: 'amsgrad'
  lr: 0.0025
  max_epoch: 150
  batch_size: 256
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
